# Generated by Django 5.2.15 on 2026-06-13 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tool_type', models.CharField(max_length=100, verbose_name='tipo')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('loaned', 'Prestado'), ('disposed', 'Dado de baja')], default='available', max_length=20)),
                ('disposal_reason', models.TextField(blank=True, verbose_name='motivo de baja')),
                ('disposal_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'herramienta',
                'verbose_name_plural': 'herramientas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ToolLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_at', models.DateTimeField(verbose_name='devolución esperada')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='devuelto en')),
                ('notes', models.TextField(blank=True)),
                ('loaned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_tool_loans', to=settings.AUTH_USER_MODEL, verbose_name='prestado por')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_tool_returns', to=settings.AUTH_USER_MODEL, verbose_name='recibido por')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='tool_loans', to=settings.AUTH_USER_MODEL, verbose_name='técnico')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='tools.tool')),
            ],
            options={
                'verbose_name': 'préstamo de herramienta',
                'verbose_name_plural': 'préstamos de herramientas',
                'ordering': ['-loaned_at'],
            },
        ),
    ]
