# Generated by Django 5.2.15 on 2026-06-13 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('application', models.CharField(blank=True, help_text='Equipo o sistema donde se aplica (e.g., Radar AN/SPS-67)', max_length=255)),
                ('location', models.CharField(help_text='Ubicación usando nomenclatura militar (e.g., E-01-A-03)', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='unidad', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('document_type', models.CharField(blank=True, choices=[('oficio', 'Oficio'), ('conduce', 'Conduce'), ('factura', 'Factura'), ('directo', 'Directo')], help_text='Tipo de documento que respalda el movimiento', max_length=20)),
                ('document_number', models.CharField(blank=True, help_text='Número de oficio, conduce o factura', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
