# Generated by Django 5.2.15 on 2026-06-17

from django.db import migrations, models
import django.db.models.deletion


def seed_abbreviations(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    abbreviation_map = {
        'Componentes': 'COM',
        'Conectores y Cableado': 'CON',
        'Soldadura y Químicos': 'SOL',
        'Ferretería': 'FER',
    }
    for name, abbr in abbreviation_map.items():
        cat = Category.objects.filter(name=name).first()
        if cat:
            cat.abbreviation = abbr
            cat.save(update_fields=['abbreviation'])


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(default='CAT', help_text='Abreviatura de 3-4 letras (e.g., COM, CON, SOL, FER)', max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('base_naval', 'Base Naval'), ('unidad_naval', 'Unidad Naval'), ('comandancia', 'Comandancia / Capitanía'), ('destacamento', 'Destacamento / Puesto')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='document_file',
            field=models.FileField(blank=True, help_text='Archivo digitalizado del documento', null=True, upload_to='movements/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, help_text='Código auto-generado (e.g., COM-001)', max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(seed_abbreviations, reverse_seed),
    ]
