# Generated by Django 5.2.15 on 2026-06-17
# Rewritten 2026-06-18: replace SQLite-only CREATE TABLE with vendor-specific ALTER TABLE.

import django.db.models.deletion
from django.db import migrations, models


def _postgres_column_exists(cursor, table, column):
    cursor.execute(
        "SELECT 1 FROM information_schema.columns WHERE table_name=%s AND column_name=%s",
        [table, column],
    )
    return cursor.fetchone() is not None


def _sqlite_column_exists(cursor, table, column):
    cursor.execute(f"SELECT 1 FROM pragma_table_info('{table}') WHERE name=%s", [column])
    return cursor.fetchone() is not None


def column_exists(cursor, table, column):
    vendor = cursor.connection.vendor
    if vendor == 'postgresql':
        return _postgres_column_exists(cursor, table, column)
    if vendor == 'sqlite':
        return _sqlite_column_exists(cursor, table, column)
    return False


def convert_location_to_fk(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if column_exists(cursor, 'inventory_item', 'location_id'):
            return
        if column_exists(cursor, 'inventory_item', 'location'):
            if vendor == 'postgresql':
                cursor.execute('ALTER TABLE inventory_item DROP COLUMN location CASCADE')
            else:
                try:
                    cursor.execute('ALTER TABLE inventory_item DROP COLUMN location')
                except Exception:
                    pass
        if vendor == 'postgresql':
            cursor.execute('ALTER TABLE inventory_item ADD COLUMN location_id BIGINT')
            cursor.execute(
                'ALTER TABLE inventory_item '
                'ADD CONSTRAINT inventory_item_location_id_fkey '
                'FOREIGN KEY (location_id) REFERENCES inventory_location(id) ON DELETE SET NULL'
            )
            cursor.execute('CREATE INDEX IF NOT EXISTS inventory_item_location_id_idx ON inventory_item (location_id)')
        else:
            cursor.execute('ALTER TABLE inventory_item ADD COLUMN location_id INTEGER REFERENCES inventory_location(id) ON DELETE SET NULL')


def reverse_convert_location_to_fk(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute('ALTER TABLE inventory_item DROP CONSTRAINT IF EXISTS inventory_item_location_id_fkey')
            cursor.execute('DROP INDEX IF EXISTS inventory_item_location_id_idx')
            if column_exists(cursor, 'inventory_item', 'location_id'):
                cursor.execute('ALTER TABLE inventory_item DROP COLUMN location_id')
            if not column_exists(cursor, 'inventory_item', 'location'):
                cursor.execute("ALTER TABLE inventory_item ADD COLUMN location VARCHAR(100) NOT NULL DEFAULT ''")
        else:
            if column_exists(cursor, 'inventory_item', 'location_id'):
                try:
                    cursor.execute('ALTER TABLE inventory_item DROP COLUMN location_id')
                except Exception:
                    pass
            if not column_exists(cursor, 'inventory_item', 'location'):
                try:
                    cursor.execute("ALTER TABLE inventory_item ADD COLUMN location VARCHAR(100) NOT NULL DEFAULT ''")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_update_inventory_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(default='CAT', help_text='Abreviatura de 3-4 letras (e.g., COM, CON, SOL, FER)', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU del sistema anterior (legado)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='document_type',
            field=models.CharField(blank=True, choices=[('oficio', 'Oficio'), ('conduce', 'Conduce'), ('factura', 'Factura'), ('directo', 'Directo'), ('legado', 'Legado')], help_text='Tipo de documento que respalda el movimiento', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='item',
                    name='location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.location'),
                ),
            ],
            database_operations=[
                migrations.RunPython(convert_location_to_fk, reverse_convert_location_to_fk),
            ],
        ),
    ]
