# Generated by Django 5.2.15 on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_update_inventory_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='abbreviation',
            field=models.CharField(default='CAT', help_text='Abreviatura de 3-4 letras (e.g., COM, CON, SOL, FER)', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU del sistema anterior (legado)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='document_type',
            field=models.CharField(blank=True, choices=[('oficio', 'Oficio'), ('conduce', 'Conduce'), ('factura', 'Factura'), ('directo', 'Directo'), ('legado', 'Legado')], help_text='Tipo de documento que respalda el movimiento', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='item',
                    name='location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.location'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'DROP TABLE IF EXISTS inventory_item_new',
                        '''CREATE TABLE inventory_item_new (
                            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                            name VARCHAR(200) NOT NULL,
                            sku VARCHAR(100),
                            part_number VARCHAR(100) NOT NULL,
                            description TEXT NOT NULL,
                            application VARCHAR(255) NOT NULL,
                            location_id INTEGER REFERENCES inventory_location(id) ON DELETE SET NULL,
                            quantity INTEGER UNSIGNED NOT NULL DEFAULT 0,
                            minimum_stock INTEGER UNSIGNED NOT NULL DEFAULT 0,
                            unit VARCHAR(50) NOT NULL DEFAULT unidad,
                            is_active BOOLEAN NOT NULL DEFAULT 1,
                            created_at DATETIME NOT NULL,
                            updated_at DATETIME NOT NULL,
                            category_id BIGINT NOT NULL REFERENCES inventory_category(id),
                            image VARCHAR(100),
                            code VARCHAR(20) UNIQUE
                        )''',
                        'INSERT INTO inventory_item_new (id, name, sku, part_number, description, application, quantity, minimum_stock, unit, is_active, created_at, updated_at, category_id, image, code) SELECT id, name, sku, part_number, description, application, quantity, minimum_stock, unit, is_active, created_at, updated_at, category_id, image, code FROM inventory_item',
                        'DROP TABLE inventory_item',
                        'ALTER TABLE inventory_item_new RENAME TO inventory_item',
                    ],
                    reverse_sql=['SELECT 1'],
                ),
            ],
        ),
    ]
