# Generated by Django 5.2.15 on 2026-06-18 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_abbreviation_alter_item_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del fabricante (opcional, ej: Motorola, Harris)', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del fabricante (opcional)', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie del activo (opcional)', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno de referencia (opcional)', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('taller', 'Taller de Electrónica'), ('base_naval', 'Base Naval'), ('unidad_naval', 'Unidad Naval'), ('comandancia', 'Comandancia / Capitanía'), ('destacamento', 'Destacamento / Puesto')], max_length=20),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('oficio', 'Oficio'), ('conduce', 'Conduce'), ('factura', 'Factura'), ('directo', 'Directo'), ('legado', 'Legado')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Almacenista que aprobó el traslado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_destination', to='inventory.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.item')),
                ('origin_location', models.ForeignKey(blank=True, help_text='Ubicación de origen (nulo si es asignación inicial)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_origin', to='inventory.location')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traslado',
                'verbose_name_plural': 'traslados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='inventory_t_item_id_f556f9_idx'), models.Index(fields=['origin_location', '-created_at'], name='inventory_t_origin__1d5223_idx'), models.Index(fields=['destination_location', '-created_at'], name='inventory_t_destina_350b25_idx'), models.Index(fields=['status', '-created_at'], name='inventory_t_status_04bfaf_idx')],
            },
        ),
    ]
