# Generated by Django 5.2.1 on 2026-06-21 19:24

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_marca_item_modelo_item_numero_serie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Número de serie físico de la unidad', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('loaned', 'Asignado / Prestado'), ('maintenance', 'En mantenimiento'), ('disposed', 'Dado de baja')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'unidad física',
                'verbose_name_plural': 'unidades físicas',
                'ordering': ['item', 'serial_number'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('consumible', 'Consumible / Repuesto'), ('herramienta', 'Herramienta / Instrumento')], default='consumible', help_text='Consumible (se descuenta de quantity) o herramienta (se rastrea por ItemUnit con serial)', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='track_by_serial',
            field=models.BooleanField(default=False, help_text='Si True, el stock se cuenta por unidades físicas con serial (ItemUnit). Solo aplica a kind=herramienta.'),
        ),
        migrations.CreateModel(
            name='ItemLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('loaned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_loans_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préstamo de unidad',
                'verbose_name_plural': 'préstamos de unidades',
                'ordering': ['-loaned_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
