# Generated by Django 5.2.1 on 2026-06-21 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_itemunit_item_kind_item_track_by_serial_itemloan'),
        ('workorders', '0005_solicitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemloan',
            name='loaned_to',
            field=models.ForeignKey(blank=True, help_text='Persona/unidad que recibe la herramienta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_loans', to='workorders.solicitante'),
        ),
        migrations.AddField(
            model_name='itemloan',
            name='loaned_to_user',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que recibe (técnico del taller)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemloan',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_loans_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='itemloan',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.itemunit'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(fields=('item', 'serial_number'), name='unique_item_unit_serial'),
        ),
        migrations.AddConstraint(
            model_name='itemloan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('item_unit',), name='unique_active_loan_per_unit'),
        ),
    ]
