# Generated by Django 5.2.1 on 2026-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_migrate_tools_to_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunit',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('asignado', 'Asignado'), ('maintenance', 'En mantenimiento'), ('disposed', 'Dado de baja')], default='available', max_length=20),
        ),
    ]
