# Generated by Django 5.2.15 on 2026-06-13 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('origin_unit', models.CharField(help_text='Unidad o buque de origen (e.g., BA-1101)', max_length=150)),
                ('delivery_officer_name', models.CharField(max_length=150, verbose_name='nombre del oficial que entrega')),
                ('delivery_officer_rank', models.CharField(blank=True, max_length=100, verbose_name='grado del oficial que entrega')),
                ('equipment_brand', models.CharField(blank=True, max_length=100)),
                ('equipment_model', models.CharField(blank=True, max_length=100)),
                ('equipment_serial', models.CharField(blank=True, max_length=100)),
                ('equipment_description', models.TextField(help_text='Descripción del equipo ingresado')),
                ('reported_failure', models.TextField(blank=True, help_text='Fallo reportado por la unidad')),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnóstico técnico')),
                ('replaced_parts_note', models.TextField(blank=True, help_text='Resumen de repuestos reemplazados')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('in_diagnosis', 'En diagnóstico'), ('waiting_parts', 'Esperando repuestos'), ('in_repair', 'En reparación'), ('ready', 'Listo para entregar'), ('delivered', 'Entregado'), ('dismissed', 'Dado de baja')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_receipt_printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workorders', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL, verbose_name='técnico asignado')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('used', 'Usado')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_parts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_parts', to='inventory.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_parts', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'repuesto de orden de trabajo',
                'verbose_name_plural': 'repuestos de órdenes de trabajo',
                'ordering': ['-created_at'],
            },
        ),
    ]
