# Generated by Django 5.2.15 on 2026-06-21 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_marca_item_modelo_item_numero_serie_and_more'),
        ('workorders', '0003_workorderpart_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workorderpart',
            name='unique_active_part_per_work_order_item',
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'approved'])), fields=('work_order', 'item'), name='unique_pending_part_per_work_order_item'),
        ),
    ]
