# Generated by Django 5.2.1 on 2026-06-21 19:24

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_itemunit_item_kind_item_track_by_serial_itemloan'),
        ('workorders', '0004_remove_workorderpart_unique_active_part_per_work_order_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del solicitante', max_length=150)),
                ('rank', models.CharField(blank=True, help_text='Rango o grado militar (opcional)', max_length=50)),
                ('agent_id', models.CharField(blank=True, help_text='Cédula militar o ID (opcional)', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, help_text='Unidad/base de procedencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitantes', to='inventory.location')),
            ],
            options={
                'verbose_name': 'solicitante',
                'verbose_name_plural': 'solicitantes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='workorders__name_6978c3_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
